/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Estado;

import controlador.ConexBd;
import controlador.FuncionesEsp;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estado;
import modelo.Pais;

/**
 *
 * @author Jov_co
 */
public class JDlgEstado extends javax.swing.JDialog {
    ArrayList<Pais> lstEstado = new ArrayList<>();
    int idPais;
    /**
     * Creates new form jDlgEstado
     */
    public JDlgEstado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillCiudades();
        listar();
    }
    public final void fillCiudades(){
        DefaultComboBoxModel mdlCbo = new DefaultComboBoxModel();
        ConexBd myConex = new ConexBd();
        jCboListaPais.removeAllItems(); //Eliminar todos los items
        Connection con = myConex.miConex();
        Pais pais = new Pais();
        mdlCbo.addElement("Seleccione un pais");
        lstEstado = pais.lstPais(con, mdlCbo);
        jCboListaPais.setModel(mdlCbo);
    }
    /*public final void fillCiudadesConsulta(String s){
        DefaultComboBoxModel mdlCbo = new DefaultComboBoxModel();
        ConexBd myConex = new ConexBd();
        jCboListaPais.removeAllItems(); //Eliminar todos los items
        Connection con = myConex.miConex();
        Pais pais = new Pais();
        mdlCbo.addElement(s);
        lstEstado = pais.lstPais(con, mdlCbo);
        jCboListaPais.setModel(mdlCbo);
    }*/
    final void listar(){
        ConexBd con = new ConexBd();
        Connection cn = con.miConex();
        Estado listaEstados = new Estado();
        jTableDatos.setModel(listaEstados.Listar(cn, jTableDatos));
    }
    void limpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) jTableDatos.getModel();
        for (int i = 0; i < jTableDatos.getRowCount(); i++){
            modelo.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboListaPais = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jBtnNuevo = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor Estados");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel2.setLayout(new java.awt.GridLayout());

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Estado", "Pais"
            }
        ));
        jTableDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDatos);
        if (jTableDatos.getColumnModel().getColumnCount() > 0) {
            jTableDatos.getColumnModel().getColumn(0).setMinWidth(50);
            jTableDatos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(527, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel4.setPreferredSize(new java.awt.Dimension(527, 150));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(60, 113));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jPanel9.setPreferredSize(new java.awt.Dimension(320, 100));
        jPanel9.setLayout(new java.awt.GridLayout(0, 2, 0, 10));

        jLabel2.setText("ID:");
        jPanel9.add(jLabel2);

        jTxtId.setEnabled(false);
        jPanel9.add(jTxtId);

        jLabel3.setText("Nombre Estado:");
        jPanel9.add(jLabel3);

        jTxtNombre.setEnabled(false);
        jPanel9.add(jTxtNombre);

        jLabel4.setText("Pais");
        jPanel9.add(jLabel4);

        jCboListaPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboListaPais.setEnabled(false);
        jCboListaPais.setPreferredSize(new java.awt.Dimension(10, 22));
        jCboListaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboListaPaisActionPerformed(evt);
            }
        });
        jPanel9.add(jCboListaPais);

        jPanel7.add(jPanel9);

        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel10.setPreferredSize(new java.awt.Dimension(40, 113));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));
        jPanel5.setPreferredSize(new java.awt.Dimension(527, 50));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jBtnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\new.png")); // NOI18N
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnNuevo);

        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/diskette.png"))); // NOI18N
        jBtnAgregar.setEnabled(false);
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnAgregar);

        jBtnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\edit.png")); // NOI18N
        jBtnModificar.setEnabled(false);
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnModificar);

        jBtnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\delete.png")); // NOI18N
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnEliminar);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\cancel.png")); // NOI18N
        jBtnCancelar.setEnabled(false);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnCancelar);

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 430, 100));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jBtnEliminar, jBtnModificar, jCboListaPais
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        // TODO add your handling code here:
        JComponent[] component1 = {
            jTxtNombre, jBtnAgregar, jBtnCancelar, jCboListaPais
        };
        JComponent[] component2 = {
            jBtnNuevo, jBtnEliminar, jBtnModificar
        };
        FuncionesEsp.DesactivarActivar(component1, true);
        FuncionesEsp.DesactivarActivar(component2, false);
        jTxtId.requestFocus();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jCboListaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboListaPaisActionPerformed
        // TODO add your handling code here:
        Pais pais;
        if((jCboListaPais.getSelectedIndex()-1)>=0){
            pais = lstEstado.get(jCboListaPais.getSelectedIndex()-1);
            idPais = pais.getId();
        }
    }//GEN-LAST:event_jCboListaPaisActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        ConexBd con = new ConexBd();
        Connection conn = con.miConex();
        Estado nuevoEstado = new Estado(jTxtNombre.getText().toLowerCase(), idPais);
        nuevoEstado.Insertar(conn);
        JOptionPane.showMessageDialog(this, "Se registro un nuevo Estado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        limpiarTabla();
        listar();
        
// Disable and Enable components
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jCboListaPais, jBtnEliminar, jBtnModificar
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        // TODO add your handling code here:
        ConexBd cnbd = new ConexBd();
        Connection conn = cnbd.miConex();
        Estado miEstado = new Estado(jTxtNombre.getText(), idPais);
        miEstado.setId(Integer.parseInt(jTxtId.getText()));
        miEstado.Editar(conn);
        JOptionPane.showMessageDialog(this, "Se modifico el estado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        limpiarTabla();
        listar();
    // Disable and Enable components       
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jBtnEliminar, jBtnModificar, jCboListaPais
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        ConexBd cnbd = new ConexBd();
        Connection conn = cnbd.miConex();
        Estado miEstado = new Estado(jTxtNombre.getText(), idPais);
        miEstado.setId(Integer.parseInt(jTxtId.getText()));
        
        if (JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar la información?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "El estado " +
                    jTxtNombre.getText().toUpperCase() + " se ha eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);
            miEstado.Eliminar(conn);

        } else {
            JOptionPane.showMessageDialog(this, "El estado " +
                    jTxtNombre.getText().toUpperCase() + " NO se ha eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
        limpiarTabla();
        listar();
        
    // Disable and Enable components       
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jBtnEliminar, jBtnModificar, jCboListaPais
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jTableDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDatosMouseClicked
        // TODO add your handling code here:
        int fila = jTableDatos.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "Selecciona una opción valida");
        }else{
            int id = Integer.parseInt((String)jTableDatos.getValueAt(fila, 0).toString());
            String nombre = (String)jTableDatos.getValueAt(fila, 1);
            String pais = (String)jTableDatos.getValueAt(fila, 2);
            jTxtId.setText("" + id);
            jTxtNombre.setText(nombre);
            jCboListaPais.setSelectedItem(pais);
            
            
    // Disable and Enable components
            JComponent[] component1 = {
                jTxtNombre, jBtnModificar, jBtnEliminar, jBtnCancelar, jCboListaPais
            };
            JComponent[] component2 = {
                jBtnNuevo, jBtnAgregar
            };
            FuncionesEsp.DesactivarActivar(component1, true);
            FuncionesEsp.DesactivarActivar(component2, false);
            jTxtNombre.requestFocus();
            
        }
    }//GEN-LAST:event_jTableDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgEstado dialog = new JDlgEstado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox<String> jCboListaPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
