/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Region;

import controlador.ConexBd;
import controlador.FuncionesEsp;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estado;
import modelo.Region;

/**
 *
 * @author Jov_co
 */
public class JDlgRegion extends javax.swing.JDialog {
    ArrayList<Estado> lstEstado = new ArrayList<>();
    int idEstado;
    /**
     * Creates new form JDlgRegion
     */
    public JDlgRegion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillCiudades();
        listar();
    }
    
    public final void fillCiudades(){
        DefaultComboBoxModel mdlCbo = new DefaultComboBoxModel();
        ConexBd myConex = new ConexBd();
        jCboListaEstado.removeAllItems(); //Eliminar todos los items
        Connection con = myConex.miConex();
        Estado estado = new Estado();
        mdlCbo.addElement("Seleccione un estado");
        lstEstado = estado.lstEstado(con, mdlCbo);
        jCboListaEstado.setModel(mdlCbo);
    }
    /*public final void fillCiudadesConsulta(String s){
        DefaultComboBoxModel mdlCbo = new DefaultComboBoxModel();
        ConexBd myConex = new ConexBd();
        jCboListaEstado.removeAllItems(); //Eliminar todos los items
        Connection con = myConex.miConex();
        Estado estado = new Estado();
        mdlCbo.addElement(s);
        lstEstado = estado.lstEstado(con, mdlCbo);
        jCboListaEstado.setModel(mdlCbo);
    }*/
    final void listar(){
        ConexBd con = new ConexBd();
        Connection cn = con.miConex();
        Region listaRegiones = new Region();
        jTableDatos.setModel(listaRegiones.Listar(cn, jTableDatos));
    }
    void limpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) jTableDatos.getModel();
        for (int i = 0; i < jTableDatos.getRowCount(); i++){
            modelo.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboListaEstado = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jBtnNuevo = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor Regiones");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel2.setLayout(new java.awt.GridLayout());

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Región", "Estado"
            }
        ));
        jTableDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDatos);
        if (jTableDatos.getColumnModel().getColumnCount() > 0) {
            jTableDatos.getColumnModel().getColumn(0).setMinWidth(50);
            jTableDatos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(40, 77));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setPreferredSize(new java.awt.Dimension(40, 77));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setLayout(new java.awt.GridLayout(0, 2, 0, 10));

        jLabel2.setText("ID: ");
        jPanel8.add(jLabel2);

        jTxtId.setEnabled(false);
        jPanel8.add(jTxtId);

        jLabel3.setText("Nombre Región:");
        jPanel8.add(jLabel3);

        jTxtNombre.setEnabled(false);
        jPanel8.add(jTxtNombre);

        jLabel4.setText("Estado");
        jPanel8.add(jLabel4);

        jCboListaEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboListaEstado.setEnabled(false);
        jCboListaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboListaEstadoActionPerformed(evt);
            }
        });
        jPanel8.add(jCboListaEstado);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 442, 124));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jBtnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\new.png")); // NOI18N
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnNuevo);

        jBtnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\diskette.png")); // NOI18N
        jBtnAgregar.setEnabled(false);
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnAgregar);

        jBtnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\edit.png")); // NOI18N
        jBtnModificar.setEnabled(false);
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnModificar);

        jBtnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\delete.png")); // NOI18N
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnEliminar);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Agencia\\src\\main\\resources\\Iconos\\cancel.png")); // NOI18N
        jBtnCancelar.setEnabled(false);
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnCancelar);

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 442, 124));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        // TODO add your handling code here:
        ConexBd cnbd = new ConexBd();
        Connection conn = cnbd.miConex();
        Region miRegion = new Region(jTxtNombre.getText(), idEstado);
        miRegion.setId(Integer.parseInt(jTxtId.getText()));
        miRegion.Editar(conn);
        JOptionPane.showMessageDialog(this, "Se modifico la región","Aviso",JOptionPane.INFORMATION_MESSAGE);
        limpiarTabla();
        listar();
    // Disable and Enable components       
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jBtnEliminar, jBtnModificar, jCboListaEstado
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        ConexBd cnbd = new ConexBd();
        Connection conn = cnbd.miConex();
        Region miRegion = new Region(jTxtNombre.getText(), idEstado);
        miRegion.setId(Integer.parseInt(jTxtId.getText()));
        
        if (JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar la información?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "La región " +
                    jTxtNombre.getText().toUpperCase() + " se ha eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);
            miRegion.Eliminar(conn);

        } else {
            JOptionPane.showMessageDialog(this, "La región " +
                    jTxtNombre.getText().toUpperCase() + " NO se ha eliminado","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
        limpiarTabla();
        listar();
        
    // Disable and Enable components       
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jBtnEliminar, jBtnModificar, jCboListaEstado
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jBtnEliminar, jBtnModificar, jCboListaEstado
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        // TODO add your handling code here:
        JComponent[] component1 = {
            jTxtNombre, jBtnAgregar, jBtnCancelar, jCboListaEstado
        };
        JComponent[] component2 = {
            jBtnNuevo, jBtnEliminar, jBtnModificar, 
        };
        FuncionesEsp.DesactivarActivar(component1, true);
        FuncionesEsp.DesactivarActivar(component2, false);
        jTxtId.requestFocus();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jCboListaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboListaEstadoActionPerformed
        // TODO add your handling code here:
        Estado estado;
        if((jCboListaEstado.getSelectedIndex()-1)>=0){
            estado = lstEstado.get(jCboListaEstado.getSelectedIndex()-1);
            idEstado = estado.getId();
        }
    }//GEN-LAST:event_jCboListaEstadoActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        ConexBd con = new ConexBd();
        Connection conn = con.miConex();
        Region nuevoRegion = new Region(jTxtNombre.getText().toLowerCase(), idEstado);
        nuevoRegion.Insertar(conn);
        JOptionPane.showMessageDialog(this, "Se registro una nueva región","Aviso",JOptionPane.INFORMATION_MESSAGE);
        limpiarTabla();
        listar();
        
// Disable and Enable components
        JComponent[] component1 = {
            jTxtId, jTxtNombre, jBtnAgregar, jBtnCancelar, jCboListaEstado, jBtnEliminar, jBtnModificar
        };
        JComponent[] component2 = {
            jBtnNuevo
        };
        JComponent[] datosLimpiar = {
            jTxtId, jTxtNombre
        };
        FuncionesEsp.DesactivarActivar(component1, false);
        FuncionesEsp.DesactivarActivar(component2, true);
        FuncionesEsp.LimpiarData(datosLimpiar);
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jTableDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDatosMouseClicked
        // TODO add your handling code here:
        int fila = jTableDatos.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "Selecciona una opción valida");
        }else{
            int id = Integer.parseInt((String)jTableDatos.getValueAt(fila, 0).toString());
            String nombre = (String)jTableDatos.getValueAt(fila, 1);
            String estado = (String)jTableDatos.getValueAt(fila, 2);
            jTxtId.setText("" + id);
            jTxtNombre.setText(nombre);
            jCboListaEstado.setSelectedItem(estado);
            
    // Disable and Enable components
            JComponent[] component1 = {
                jTxtNombre, jBtnModificar, jBtnEliminar, jBtnCancelar, jCboListaEstado
            };
            JComponent[] component2 = {
                jBtnNuevo, jBtnAgregar
            };
            FuncionesEsp.DesactivarActivar(component1, true);
            FuncionesEsp.DesactivarActivar(component2, false);
            jTxtNombre.requestFocus();
            
        }
    }//GEN-LAST:event_jTableDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRegion dialog = new JDlgRegion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox<String> jCboListaEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
